#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.17 AS base
WORKDIR /app
COPY ./startup.sh .
RUN apk add --no-cache --upgrade bash \
	&& apk add --no-cache curl \
	&& apk add --no-cache screen

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.17 AS build
WORKDIR /src
COPY ["H4x2-Node/H4x2-Node.csproj", "H4x2-Node/"]
RUN dotnet restore "H4x2-Node/H4x2-Node.csproj"
COPY . .
WORKDIR "/src/H4x2-Node"
RUN dotnet build "H4x2-Node.csproj" -c Release -o /app/build
RUN dotnet tool install --global Tide-Key \
	&& dotnet tool install localtunnel.cli --global

FROM build AS publish
RUN dotnet publish "H4x2-Node.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /ork
RUN mkdir priv \
	&& mkdir db \
	&& touch priv/key.txt \
	&& chmod 600 priv/key.txt \
	&& chmod 700 /app/startup.sh
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=build /root/.dotnet/tools/ /opt/bin
ENV PATH="/opt/bin:${PATH}"
ENTRYPOINT ["bash", "startup.sh"]