@startuml H4x2_prism
title Tide PRISM authentication
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/aws-orange-light/puml-theme-aws-orange-light.puml

actor "User" as usr
collections "Servers" as ork

group Precondition
note over usr
    username
    password
end note 

note over ork
    ORKPriv
    ORKPub = G * ORKPriv

    userID = hash(username)
    PrismAuth = hash( ORKPriv * [G * hash(a * Prism)] ) 
    Prism = 32 byte number
end note
end

note over usr
a = Point(password)
userID = hash(username)
r = random()
endnote

usr -> ork: a * r, userID
note over ork
[CHECK] userID exists -> if so -> get user's Prism
endnote
ork -> usr: a * r * Prism, ORKPub

note over usr
keyPoint = (a * r * Prism) * r^-1  (remove r)
keyAES = hash( ORKPub * hash(keyPoint) )

encryptedData = encrypt(keyAES, "PrismAuth")
endnote

usr -> ork: encryptedData, userID

note over ork
Get PrismAuth for this userID
[CHECK] decrypt(PrismAuth, decryptedData) = "PrismAuth"
endnote

ork -> usr: Let them know they've succeeded somehow
@enduml