@startuml H4x2 User Flow
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/aws-orange-light/puml-theme-aws-orange-light.puml


title H4x2 User Flow

partition "**precondition**" {
    :password : Attempted password
    PRISM : Augmented password
    PRISMi : Partial of a PRISM.  Each node holds a PRISMi
    ORK 1 - Closed Node
    ORK 2 - Exposed Node
    Criteria - IP not throttled and Password is correct
    ]
}
-[#white,dashed]->;

start
->request Page;
:Enter password;
:Blur password;
:Send to ORK Nodes;
partition "**ORK Nodes**" {
    if (is ORK 1?) then (no)
        partition "**ORK 2**" {
        :Send PRISMi;
        }
    else (yes)
        partition "**ORK 1**" {
            if (Criteria met?) then (yes)
                :Apply Function (PRF) to\n the blurred password;
            else (no)
                :Send random response;
            endif
        }
    
    endif    
}

->result;
:Assemble and Test PRISM;
if (PRISM correct?) then (yes)
    if (example) then 
        :Display "This is an Example";
        elseif(prize) then
        :Display "Congratulation the code is ...";
    endif
    else (no)
        :display random message;  
endif

note 
    Function returns 
    number of seconds to 
    throttle.
    0 if not throttled.
endnote
stop 

@enduml